-- =====================================================================
-- V1: Core schema for the Australia Hospital Billing System
--
-- Conventions
--   * Every business table carries tenant_id (row-level multi-tenancy).
--     Hibernate's @TenantId appends "tenant_id = ?" to every query.
--   * Surrogate keys are BIGINT identity columns.
--   * Money is NUMERIC(12,2) in AUD. Never floating point.
--   * created_at / updated_at are TIMESTAMPTZ; business dates are local
--     Australia/Sydney TIMESTAMP / DATE values (see NOTES on the ER diagram).
--   * version supports JPA optimistic locking (@Version).
-- =====================================================================

-- ---------------------------------------------------------------------
-- Tenant registry (not tenant-scoped itself)
-- ---------------------------------------------------------------------
CREATE TABLE hospital (
    id              UUID            PRIMARY KEY,
    code            VARCHAR(30)     NOT NULL UNIQUE,
    name            VARCHAR(150)    NOT NULL,
    hospital_type   VARCHAR(20)     NOT NULL,          -- PUBLIC | PRIVATE
    abn             VARCHAR(20),
    state           VARCHAR(10)     NOT NULL,
    active          BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------
-- Security
-- ---------------------------------------------------------------------
CREATE TABLE app_user (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID            NOT NULL REFERENCES hospital (id),
    username        VARCHAR(60)     NOT NULL UNIQUE,
    password_hash   VARCHAR(100)    NOT NULL,
    full_name       VARCHAR(120)    NOT NULL,
    email           VARCHAR(120),
    role            VARCHAR(20)     NOT NULL,
    active          BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ,
    version         BIGINT          NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------------
-- Providers
-- ---------------------------------------------------------------------
CREATE TABLE department (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID            NOT NULL REFERENCES hospital (id),
    department_name VARCHAR(100)    NOT NULL,
    location        VARCHAR(100),
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ,
    version         BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_department_name UNIQUE (tenant_id, department_name)
);

CREATE TABLE doctor (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           UUID            NOT NULL REFERENCES hospital (id),
    department_id       BIGINT          NOT NULL REFERENCES department (id),
    first_name          VARCHAR(60)     NOT NULL,
    last_name           VARCHAR(60)     NOT NULL,
    specialization      VARCHAR(100)    NOT NULL,
    phone               VARCHAR(20),
    email               VARCHAR(120),
    provider_no         VARCHAR(10)     NOT NULL,       -- Medicare provider number
    consultation_fee    NUMERIC(12,2)   NOT NULL,
    mbs_item_no         VARCHAR(10)     NOT NULL,       -- MBS item billed per consult
    mbs_schedule_fee    NUMERIC(12,2)   NOT NULL,
    active              BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ,
    version             BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_doctor_provider_no UNIQUE (tenant_id, provider_no)
);

-- ---------------------------------------------------------------------
-- Patients
-- ---------------------------------------------------------------------
CREATE TABLE patient (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID            NOT NULL REFERENCES hospital (id),
    mrn             VARCHAR(20)     NOT NULL,           -- medical record number
    first_name      VARCHAR(60)     NOT NULL,
    last_name       VARCHAR(60)     NOT NULL,
    dob             DATE            NOT NULL,
    gender          VARCHAR(10)     NOT NULL,
    phone           VARCHAR(20),
    email           VARCHAR(120),
    address         VARCHAR(200),
    suburb          VARCHAR(80),
    state           VARCHAR(10),
    postcode        VARCHAR(4),
    country         VARCHAR(60)     NOT NULL DEFAULT 'Australia',
    medicare_no     VARCHAR(10),
    medicare_irn    SMALLINT,
    status          VARCHAR(20)     NOT NULL DEFAULT 'ACTIVE',
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ,
    version         BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_patient_mrn UNIQUE (tenant_id, mrn)
);

CREATE TABLE patient_contact (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID            NOT NULL REFERENCES hospital (id),
    patient_id      BIGINT          NOT NULL REFERENCES patient (id) ON DELETE CASCADE,
    name            VARCHAR(120)    NOT NULL,
    relation        VARCHAR(40)     NOT NULL,
    phone           VARCHAR(20)     NOT NULL,
    email           VARCHAR(120),
    is_primary      BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ,
    version         BIGINT          NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------------
-- Admissions, rooms and beds
-- ---------------------------------------------------------------------
CREATE TABLE admission_type (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID            NOT NULL REFERENCES hospital (id),
    code            VARCHAR(30)     NOT NULL,
    type_name       VARCHAR(80)     NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ,
    version         BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_admission_type_code UNIQUE (tenant_id, code)
);

CREATE TABLE admission (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           UUID            NOT NULL REFERENCES hospital (id),
    admission_no        VARCHAR(30)     NOT NULL,
    patient_id          BIGINT          NOT NULL REFERENCES patient (id),
    doctor_id           BIGINT          NOT NULL REFERENCES doctor (id),
    admission_type_id   BIGINT          NOT NULL REFERENCES admission_type (id),
    financial_class     VARCHAR(20)     NOT NULL,       -- PUBLIC | PRIVATE patient election
    admission_date      TIMESTAMP       NOT NULL,
    discharge_date      TIMESTAMP,
    diagnosis           VARCHAR(500),
    status              VARCHAR(20)     NOT NULL,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ,
    version             BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_admission_no UNIQUE (tenant_id, admission_no),
    CONSTRAINT ck_admission_dates CHECK (discharge_date IS NULL OR discharge_date >= admission_date)
);

CREATE TABLE room (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID            NOT NULL REFERENCES hospital (id),
    room_no         VARCHAR(20)     NOT NULL,
    bed_no          VARCHAR(10)     NOT NULL,
    room_type       VARCHAR(20)     NOT NULL,
    daily_rate      NUMERIC(12,2)   NOT NULL,
    status          VARCHAR(20)     NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ,
    version         BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_room_bed UNIQUE (tenant_id, room_no, bed_no)
);

CREATE TABLE room_allocation (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID            NOT NULL REFERENCES hospital (id),
    admission_id    BIGINT          NOT NULL REFERENCES admission (id),
    room_id         BIGINT          NOT NULL REFERENCES room (id),
    from_date       TIMESTAMP       NOT NULL,
    to_date         TIMESTAMP,
    charge_per_day  NUMERIC(12,2)   NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ,
    version         BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT ck_allocation_dates CHECK (to_date IS NULL OR to_date > from_date)
);

-- ---------------------------------------------------------------------
-- Insurance
-- ---------------------------------------------------------------------
CREATE TABLE insurance_company (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID            NOT NULL REFERENCES hospital (id),
    company_name    VARCHAR(120)    NOT NULL,
    payer_type      VARCHAR(20)     NOT NULL,           -- MEDICARE | PRIVATE_FUND
    network_status  VARCHAR(20)     NOT NULL,           -- NO_GAP | KNOWN_GAP | NON_PARTICIPATING | NOT_APPLICABLE
    known_gap_cap   NUMERIC(12,2),                      -- max patient gap per medical item (KNOWN_GAP)
    abn             VARCHAR(20),
    contact_person  VARCHAR(120),
    phone           VARCHAR(20),
    email           VARCHAR(120),
    address         VARCHAR(200),
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ,
    version         BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_company_name UNIQUE (tenant_id, company_name)
);

CREATE TABLE insurance_policy (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID            NOT NULL REFERENCES hospital (id),
    patient_id      BIGINT          NOT NULL REFERENCES patient (id),
    company_id      BIGINT          NOT NULL REFERENCES insurance_company (id),
    policy_no       VARCHAR(40)     NOT NULL,
    cover_tier      VARCHAR(20)     NOT NULL,
    excess_amount   NUMERIC(12,2)   NOT NULL DEFAULT 0,
    annual_limit    NUMERIC(12,2)   NOT NULL,
    benefits_used   NUMERIC(12,2)   NOT NULL DEFAULT 0, -- benefit accumulator
    start_date      DATE            NOT NULL,
    end_date        DATE,
    status          VARCHAR(20)     NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ,
    version         BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_policy_no UNIQUE (tenant_id, company_id, policy_no)
);

-- ---------------------------------------------------------------------
-- Laboratory
-- ---------------------------------------------------------------------
CREATE TABLE lab_test (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           UUID            NOT NULL REFERENCES hospital (id),
    test_code           VARCHAR(20)     NOT NULL,
    test_name           VARCHAR(120)    NOT NULL,
    category            VARCHAR(60)     NOT NULL,
    unit_price          NUMERIC(12,2)   NOT NULL,
    mbs_item_no         VARCHAR(10),
    mbs_schedule_fee    NUMERIC(12,2),
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ,
    version             BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_lab_test_code UNIQUE (tenant_id, test_code)
);

CREATE TABLE lab_order (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID            NOT NULL REFERENCES hospital (id),
    order_no        VARCHAR(30)     NOT NULL,
    admission_id    BIGINT          NOT NULL REFERENCES admission (id),
    doctor_id       BIGINT          NOT NULL REFERENCES doctor (id),
    order_date      TIMESTAMP       NOT NULL,
    status          VARCHAR(20)     NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ,
    version         BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_lab_order_no UNIQUE (tenant_id, order_no)
);

CREATE TABLE lab_order_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID            NOT NULL REFERENCES hospital (id),
    lab_order_id    BIGINT          NOT NULL REFERENCES lab_order (id) ON DELETE CASCADE,
    lab_test_id     BIGINT          NOT NULL REFERENCES lab_test (id),
    quantity        INTEGER         NOT NULL CHECK (quantity > 0),
    price           NUMERIC(12,2)   NOT NULL,
    result          VARCHAR(500),
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ,
    version         BIGINT          NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------------
-- Pharmacy
-- ---------------------------------------------------------------------
CREATE TABLE medicine (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID            NOT NULL REFERENCES hospital (id),
    medicine_name   VARCHAR(120)    NOT NULL,
    category        VARCHAR(60)     NOT NULL,
    unit_price      NUMERIC(12,2)   NOT NULL,
    gst_rate        NUMERIC(5,4)    NOT NULL DEFAULT 0, -- 0.1000 = 10% GST, 0 = GST-free
    stock_quantity  INTEGER         NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ,
    version         BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_medicine_name UNIQUE (tenant_id, medicine_name)
);

CREATE TABLE pharmacy_prescription (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           UUID            NOT NULL REFERENCES hospital (id),
    prescription_no     VARCHAR(30)     NOT NULL,
    admission_id        BIGINT          NOT NULL REFERENCES admission (id),
    doctor_id           BIGINT          NOT NULL REFERENCES doctor (id),
    prescription_date   TIMESTAMP       NOT NULL,
    status              VARCHAR(20)     NOT NULL,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ,
    version             BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_prescription_no UNIQUE (tenant_id, prescription_no)
);

CREATE TABLE prescription_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID            NOT NULL REFERENCES hospital (id),
    prescription_id BIGINT          NOT NULL REFERENCES pharmacy_prescription (id) ON DELETE CASCADE,
    medicine_id     BIGINT          NOT NULL REFERENCES medicine (id),
    quantity        INTEGER         NOT NULL CHECK (quantity > 0),
    dose            VARCHAR(60)     NOT NULL,
    frequency       VARCHAR(60)     NOT NULL,
    unit_price      NUMERIC(12,2)   NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ,
    version         BIGINT          NOT NULL DEFAULT 0
);

-- ---------------------------------------------------------------------
-- Billing
-- ---------------------------------------------------------------------
CREATE TABLE hospital_bill (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id               UUID            NOT NULL REFERENCES hospital (id),
    bill_no                 VARCHAR(30)     NOT NULL,
    admission_id            BIGINT          NOT NULL REFERENCES admission (id),
    bill_date               TIMESTAMP       NOT NULL,
    gross_amount            NUMERIC(12,2)   NOT NULL DEFAULT 0,
    discount_amount         NUMERIC(12,2)   NOT NULL DEFAULT 0,
    gst_amount              NUMERIC(12,2)   NOT NULL DEFAULT 0,
    net_amount              NUMERIC(12,2)   NOT NULL DEFAULT 0,
    medicare_amount         NUMERIC(12,2)   NOT NULL DEFAULT 0,
    insurance_amount        NUMERIC(12,2)   NOT NULL DEFAULT 0,
    patient_payable_amount  NUMERIC(12,2)   NOT NULL DEFAULT 0,
    paid_amount             NUMERIC(12,2)   NOT NULL DEFAULT 0,
    status                  VARCHAR(20)     NOT NULL,
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ,
    version                 BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_bill_no UNIQUE (tenant_id, bill_no)
);

CREATE TABLE bill_item (
    id                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id                   UUID            NOT NULL REFERENCES hospital (id),
    hospital_bill_id            BIGINT          NOT NULL REFERENCES hospital_bill (id) ON DELETE CASCADE,
    item_type                   VARCHAR(20)     NOT NULL,   -- ROOM, DOCTOR, CONSULTATION, SURGERY, PROCEDURE, LAB, PHARMACY, NURSING, EQUIPMENT, OTHER
    reference_id                BIGINT,
    description                 VARCHAR(250)    NOT NULL,
    mbs_item_no                 VARCHAR(10),
    mbs_schedule_fee            NUMERIC(12,2),
    quantity                    NUMERIC(10,2)   NOT NULL,
    unit_price                  NUMERIC(12,2)   NOT NULL,
    gross_amount                NUMERIC(12,2)   NOT NULL,
    discount_amount             NUMERIC(12,2)   NOT NULL DEFAULT 0,
    gst_amount                  NUMERIC(12,2)   NOT NULL DEFAULT 0,
    net_amount                  NUMERIC(12,2)   NOT NULL,
    medicare_benefit            NUMERIC(12,2)   NOT NULL DEFAULT 0,
    insurance_covered_amount    NUMERIC(12,2)   NOT NULL DEFAULT 0,
    patient_amount              NUMERIC(12,2)   NOT NULL DEFAULT 0,
    created_at                  TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMPTZ,
    version                     BIGINT          NOT NULL DEFAULT 0
);

CREATE TABLE payment (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           UUID            NOT NULL REFERENCES hospital (id),
    payment_no          VARCHAR(30)     NOT NULL,
    hospital_bill_id    BIGINT          NOT NULL REFERENCES hospital_bill (id),
    payment_date        TIMESTAMP       NOT NULL,
    amount              NUMERIC(12,2)   NOT NULL CHECK (amount > 0),
    refunded_amount     NUMERIC(12,2)   NOT NULL DEFAULT 0,
    payment_mode        VARCHAR(30)     NOT NULL,
    paid_by             VARCHAR(20)     NOT NULL,       -- PATIENT | MEDICARE | PRIVATE_FUND
    transaction_no      VARCHAR(60),
    status              VARCHAR(20)     NOT NULL,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ,
    version             BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_payment_no UNIQUE (tenant_id, payment_no)
);

CREATE TABLE refund (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID            NOT NULL REFERENCES hospital (id),
    refund_no       VARCHAR(30)     NOT NULL,
    payment_id      BIGINT          NOT NULL REFERENCES payment (id),
    refund_date     TIMESTAMP       NOT NULL,
    amount          NUMERIC(12,2)   NOT NULL CHECK (amount > 0),
    reason          VARCHAR(250)    NOT NULL,
    status          VARCHAR(20)     NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ,
    version         BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_refund_no UNIQUE (tenant_id, refund_no)
);

-- ---------------------------------------------------------------------
-- Claims & Explanation of Benefits
-- ---------------------------------------------------------------------
CREATE TABLE insurance_claim (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           UUID            NOT NULL REFERENCES hospital (id),
    claim_no            VARCHAR(30)     NOT NULL,
    hospital_bill_id    BIGINT          NOT NULL REFERENCES hospital_bill (id),
    admission_id        BIGINT          NOT NULL REFERENCES admission (id),
    company_id          BIGINT          NOT NULL REFERENCES insurance_company (id),
    policy_id           BIGINT          REFERENCES insurance_policy (id),  -- NULL for Medicare
    payer_type          VARCHAR(20)     NOT NULL,
    authorization_no    VARCHAR(40),
    claim_date          TIMESTAMP       NOT NULL,
    claimed_amount      NUMERIC(12,2)   NOT NULL DEFAULT 0,
    approved_amount     NUMERIC(12,2)   NOT NULL DEFAULT 0,
    rejected_amount     NUMERIC(12,2)   NOT NULL DEFAULT 0,
    paid_amount         NUMERIC(12,2)   NOT NULL DEFAULT 0,
    status              VARCHAR(30)     NOT NULL,
    payer_reference     VARCHAR(60),
    rejection_reason    VARCHAR(500),
    submitted_at        TIMESTAMP,
    adjudicated_at      TIMESTAMP,
    paid_at             TIMESTAMP,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ,
    version             BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_claim_no UNIQUE (tenant_id, claim_no),
    -- one claim per payer per bill: backs DuplicateClaimException at DB level
    CONSTRAINT uk_claim_bill_payer UNIQUE (tenant_id, hospital_bill_id, company_id)
);

CREATE TABLE claim_item (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           UUID            NOT NULL REFERENCES hospital (id),
    claim_id            BIGINT          NOT NULL REFERENCES insurance_claim (id) ON DELETE CASCADE,
    bill_item_id        BIGINT          NOT NULL REFERENCES bill_item (id),
    claimed_amount      NUMERIC(12,2)   NOT NULL,
    approved_amount     NUMERIC(12,2)   NOT NULL DEFAULT 0,
    rejected_amount     NUMERIC(12,2)   NOT NULL DEFAULT 0,
    rejection_reason    VARCHAR(250),
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ,
    version             BIGINT          NOT NULL DEFAULT 0
);

CREATE TABLE claim_status_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID            NOT NULL REFERENCES hospital (id),
    claim_id        BIGINT          NOT NULL REFERENCES insurance_claim (id) ON DELETE CASCADE,
    from_status     VARCHAR(30),
    to_status       VARCHAR(30)     NOT NULL,
    note            VARCHAR(500),
    changed_at      TIMESTAMP       NOT NULL,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ,
    version         BIGINT          NOT NULL DEFAULT 0
);

CREATE TABLE explanation_of_benefit (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id               UUID            NOT NULL REFERENCES hospital (id),
    eob_no                  VARCHAR(30)     NOT NULL,
    claim_id                BIGINT          NOT NULL UNIQUE REFERENCES insurance_claim (id),
    issued_at               TIMESTAMP       NOT NULL,
    total_charged           NUMERIC(12,2)   NOT NULL,
    total_benefit           NUMERIC(12,2)   NOT NULL,
    patient_responsibility  NUMERIC(12,2)   NOT NULL,
    summary                 VARCHAR(1000),
    created_at              TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at              TIMESTAMPTZ,
    version                 BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_eob_no UNIQUE (tenant_id, eob_no)
);

-- Human-friendly document numbers (BILL-2026-000001, CLM-..., etc.)
CREATE SEQUENCE document_number_seq START WITH 1000 INCREMENT BY 1;
