-- =====================================================================
-- V4: End-to-end clinical workflow and tax invoicing
--   * BILLING role renamed to BILLING_OFFICER (self-registration roles)
--   * Bed status MAINTENANCE renamed to UNDER_MAINTENANCE
--   * Care setting (IPD / OPD) on admissions -> Medicare 75% vs 85% rebate
--   * Doctor schedules (weekly roster) and consultations per admission
--   * Bill line-item locking at discharge and FULL / PARTIAL / PENDING payment status
--   * Hospital contact details for the tax invoice header
-- =====================================================================

-- ---------------------------------------------------------------------
-- Reference-data renames
-- ---------------------------------------------------------------------
UPDATE app_user SET role = 'BILLING_OFFICER' WHERE role = 'BILLING';
UPDATE room     SET status = 'UNDER_MAINTENANCE' WHERE status = 'MAINTENANCE';

ALTER TABLE app_user ADD CONSTRAINT ck_app_user_role
    CHECK (role IN ('ADMIN', 'BILLING_OFFICER', 'DOCTOR', 'RECEPTIONIST', 'LAB', 'PHARMACY'));
ALTER TABLE room ADD CONSTRAINT ck_room_status
    CHECK (status IN ('AVAILABLE', 'OCCUPIED', 'UNDER_MAINTENANCE'));

-- ---------------------------------------------------------------------
-- Hospital letterhead (tax invoice header)
-- ---------------------------------------------------------------------
ALTER TABLE hospital
    ADD COLUMN address_line VARCHAR(150),
    ADD COLUMN suburb       VARCHAR(60),
    ADD COLUMN postcode     VARCHAR(4),
    ADD COLUMN phone        VARCHAR(20),
    ADD COLUMN email        VARCHAR(120);

UPDATE hospital SET address_line = '1 Harbour Bridge Road', suburb = 'Sydney', postcode = '2000',
                    phone = '0291110000', email = 'accounts@harbour.example.au'
WHERE id = '11111111-1111-4111-8111-111111111111';
UPDATE hospital SET address_line = '300 Grattan Street', suburb = 'Parkville', postcode = '3050',
                    phone = '0391110000', email = 'accounts@melbgen.example.au'
WHERE id = '22222222-2222-4222-8222-222222222222';

-- ---------------------------------------------------------------------
-- Admissions: inpatient (IPD) or outpatient (OPD)
-- ---------------------------------------------------------------------
ALTER TABLE admission ADD COLUMN care_setting VARCHAR(10) NOT NULL DEFAULT 'IPD';
ALTER TABLE admission ADD CONSTRAINT ck_admission_care_setting CHECK (care_setting IN ('IPD', 'OPD'));

-- ---------------------------------------------------------------------
-- Doctor weekly schedule (roster)
-- ---------------------------------------------------------------------
CREATE TABLE doctor_schedule (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       UUID            NOT NULL REFERENCES hospital (id),
    doctor_id       BIGINT          NOT NULL REFERENCES doctor (id),
    day_of_week     VARCHAR(10)     NOT NULL,          -- MONDAY .. SUNDAY (java.time.DayOfWeek)
    start_time      TIME            NOT NULL,
    end_time        TIME            NOT NULL,
    slot_minutes    INTEGER         NOT NULL DEFAULT 15 CHECK (slot_minutes BETWEEN 5 AND 120),
    location        VARCHAR(100),
    active          BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ,
    version         BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT ck_schedule_times CHECK (end_time > start_time),
    CONSTRAINT ck_schedule_day CHECK (day_of_week IN
        ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'))
);
CREATE INDEX ix_schedule_tenant_doctor ON doctor_schedule (tenant_id, doctor_id, day_of_week);

-- ---------------------------------------------------------------------
-- Consultations (doctor attendances) attached to an admission
-- ---------------------------------------------------------------------
CREATE TABLE consultation (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           UUID            NOT NULL REFERENCES hospital (id),
    consultation_no     VARCHAR(30)     NOT NULL,
    admission_id        BIGINT          NOT NULL REFERENCES admission (id),
    doctor_id           BIGINT          NOT NULL REFERENCES doctor (id),
    consultation_type   VARCHAR(20)     NOT NULL,      -- INITIAL | FOLLOW_UP | SPECIALIST_REVIEW | TELEHEALTH
    consultation_at     TIMESTAMP       NOT NULL,
    mbs_item_no         VARCHAR(10)     NOT NULL,
    mbs_schedule_fee    NUMERIC(12,2)   NOT NULL CHECK (mbs_schedule_fee >= 0),
    fee                 NUMERIC(12,2)   NOT NULL CHECK (fee >= 0),
    notes               VARCHAR(500),
    status              VARCHAR(20)     NOT NULL DEFAULT 'COMPLETED',  -- COMPLETED | CANCELLED
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ,
    version             BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT uk_consultation_no UNIQUE (tenant_id, consultation_no)
);
CREATE INDEX ix_consultation_tenant_admission ON consultation (tenant_id, admission_id);
CREATE INDEX ix_consultation_doctor_time ON consultation (tenant_id, doctor_id, consultation_at);

-- ---------------------------------------------------------------------
-- Billing: locked lines and customer-facing payment status
-- ---------------------------------------------------------------------
ALTER TABLE bill_item ADD COLUMN locked BOOLEAN NOT NULL DEFAULT FALSE;

-- payment_status describes the PATIENT's share (what the tax invoice shows as "balance due"):
--   PENDING = nothing paid yet, PARTIAL = part paid, FULL = patient share settled.
ALTER TABLE hospital_bill
    ADD COLUMN patient_paid_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    ADD COLUMN payment_status      VARCHAR(10)   NOT NULL DEFAULT 'PENDING',
    ADD COLUMN charges_locked_at   TIMESTAMP;
ALTER TABLE hospital_bill ADD CONSTRAINT ck_bill_payment_status
    CHECK (payment_status IN ('PENDING', 'PARTIAL', 'FULL'));

UPDATE hospital_bill b
SET patient_paid_amount = COALESCE((SELECT SUM(p.amount - p.refunded_amount)
                                    FROM payment p
                                    WHERE p.hospital_bill_id = b.id AND p.paid_by = 'PATIENT'), 0);

UPDATE hospital_bill
SET payment_status = CASE
        WHEN status IN ('DRAFT', 'CANCELLED') THEN 'PENDING'
        WHEN patient_paid_amount >= patient_payable_amount THEN 'FULL'
        WHEN patient_paid_amount > 0 THEN 'PARTIAL'
        ELSE 'PENDING' END;

-- ---------------------------------------------------------------------
-- Demo roster: Mon-Fri clinics for every Sydney doctor, Saturday ED cover
-- ---------------------------------------------------------------------
INSERT INTO doctor_schedule (tenant_id, doctor_id, day_of_week, start_time, end_time, slot_minutes, location)
SELECT d.tenant_id, d.id, dow.day, TIME '08:00', TIME '17:00', 20, dep.department_name || ' Clinic'
FROM doctor d
JOIN department dep ON dep.id = d.department_id
CROSS JOIN (VALUES ('MONDAY'), ('TUESDAY'), ('WEDNESDAY'), ('THURSDAY'), ('FRIDAY')) AS dow(day);

INSERT INTO doctor_schedule (tenant_id, doctor_id, day_of_week, start_time, end_time, slot_minutes, location)
SELECT d.tenant_id, d.id, 'SATURDAY', TIME '09:00', TIME '13:00', 15, 'Emergency Department'
FROM doctor d
WHERE d.provider_no = '4567890F';
