-- =====================================================================
-- V5: Lab / pharmacy work queues, audit trail ("who did what"),
--     GST classification of the catalogues and a standard catalogue
--     for EVERY hospital (tenant).
--
-- MBS item numbers and schedule fees below are demo values. Check them
-- against MBS Online (https://www.mbsonline.gov.au) before real use.
-- =====================================================================

-- ---------------------------------------------------------------------
-- Lab test catalogue: type, GST flag, active flag
-- ---------------------------------------------------------------------
ALTER TABLE lab_test
    ADD COLUMN test_type VARCHAR(20) NOT NULL DEFAULT 'PATHOLOGY',
    ADD COLUMN gst_free  BOOLEAN     NOT NULL DEFAULT TRUE,
    ADD COLUMN active    BOOLEAN     NOT NULL DEFAULT TRUE;
ALTER TABLE lab_test ADD CONSTRAINT ck_lab_test_type CHECK (test_type IN ('PATHOLOGY', 'IMAGING', 'DIAGNOSTIC'));

UPDATE lab_test SET test_type = 'IMAGING'    WHERE category ILIKE 'imaging%' OR category ILIKE 'radiology%';
UPDATE lab_test SET test_type = 'DIAGNOSTIC' WHERE test_code = 'ECG';

-- ---------------------------------------------------------------------
-- Lab order audit trail
-- ---------------------------------------------------------------------
ALTER TABLE lab_order
    ADD COLUMN ordered_by_user_id   BIGINT REFERENCES app_user (id),
    ADD COLUMN ordered_by_name      VARCHAR(120),
    ADD COLUMN collected_by_user_id BIGINT REFERENCES app_user (id),
    ADD COLUMN collected_by_name    VARCHAR(120),
    ADD COLUMN collected_at         TIMESTAMP,
    ADD COLUMN performed_by_user_id BIGINT REFERENCES app_user (id),
    ADD COLUMN performed_by_name    VARCHAR(120),
    ADD COLUMN completed_at         TIMESTAMP,
    ADD COLUMN result_notes         VARCHAR(1000),
    ADD COLUMN cancelled_by_name    VARCHAR(120),
    ADD COLUMN cancelled_at         TIMESTAMP;

ALTER TABLE lab_order_item
    ADD COLUMN resulted_by_name VARCHAR(120),
    ADD COLUMN resulted_at      TIMESTAMP;

CREATE INDEX ix_lab_order_queue ON lab_order (tenant_id, status, order_date);

-- ---------------------------------------------------------------------
-- Medicine catalogue: GST classification (Australian GST Act)
--   PBS            PBS-listed medicine                       GST-free
--   PRESCRIPTION   prescription-only (non-PBS) on a script   GST-free
--   OTC            over-the-counter product                  10% GST
--   TAXABLE_SUPPLY general / non-medical goods               10% GST
-- gst_rate is kept (the billing engine reads it) and must match the category.
-- ---------------------------------------------------------------------
ALTER TABLE medicine
    ADD COLUMN supply_category        VARCHAR(20) NOT NULL DEFAULT 'PBS',
    ADD COLUMN pbs_item_code          VARCHAR(10),
    ADD COLUMN active                 BOOLEAN     NOT NULL DEFAULT TRUE,
    ADD COLUMN stock_adjusted_by_name VARCHAR(120),
    ADD COLUMN stock_adjusted_at      TIMESTAMP;

UPDATE medicine SET supply_category = CASE WHEN gst_rate > 0 THEN 'TAXABLE_SUPPLY' ELSE 'PBS' END;
UPDATE medicine SET gst_rate = CASE WHEN supply_category IN ('PBS', 'PRESCRIPTION') THEN 0 ELSE 0.1 END;

ALTER TABLE medicine ADD CONSTRAINT ck_medicine_supply_category
    CHECK (supply_category IN ('PBS', 'PRESCRIPTION', 'OTC', 'TAXABLE_SUPPLY'));
ALTER TABLE medicine ADD CONSTRAINT ck_medicine_gst_matches_category
    CHECK ((supply_category IN ('PBS', 'PRESCRIPTION') AND gst_rate = 0)
        OR (supply_category IN ('OTC', 'TAXABLE_SUPPLY') AND gst_rate = 0.1));

-- ---------------------------------------------------------------------
-- Prescription audit trail
-- ---------------------------------------------------------------------
ALTER TABLE pharmacy_prescription
    ADD COLUMN prescribed_by_user_id BIGINT REFERENCES app_user (id),
    ADD COLUMN prescribed_by_name    VARCHAR(120),
    ADD COLUMN dispensed_by_user_id  BIGINT REFERENCES app_user (id),
    ADD COLUMN dispensed_by_name     VARCHAR(120),
    ADD COLUMN dispensed_at          TIMESTAMP,
    ADD COLUMN cancelled_by_name     VARCHAR(120),
    ADD COLUMN cancelled_at          TIMESTAMP;

CREATE INDEX ix_prescription_queue ON pharmacy_prescription (tenant_id, status, prescription_date);

-- ---------------------------------------------------------------------
-- Stock ledger: every change to stock_quantity, with who and why
-- ---------------------------------------------------------------------
CREATE TABLE medicine_stock_movement (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id           UUID            NOT NULL REFERENCES hospital (id),
    medicine_id         BIGINT          NOT NULL REFERENCES medicine (id),
    movement_type       VARCHAR(20)     NOT NULL,      -- OPENING | RECEIPT | ADJUSTMENT | DISPENSE
    quantity_delta      INTEGER         NOT NULL,
    balance_after       INTEGER         NOT NULL CHECK (balance_after >= 0),
    reason              VARCHAR(250),
    prescription_id     BIGINT          REFERENCES pharmacy_prescription (id),
    performed_by_user_id BIGINT         REFERENCES app_user (id),
    performed_by_name   VARCHAR(120)    NOT NULL,
    performed_at        TIMESTAMP       NOT NULL,
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ,
    version             BIGINT          NOT NULL DEFAULT 0,
    CONSTRAINT ck_stock_movement_type CHECK (movement_type IN ('OPENING', 'RECEIPT', 'ADJUSTMENT', 'DISPENSE'))
);
CREATE INDEX ix_stock_movement_medicine ON medicine_stock_movement (tenant_id, medicine_id, performed_at);
CREATE INDEX ix_stock_movement_prescription ON medicine_stock_movement (prescription_id);

-- ---------------------------------------------------------------------
-- Standard pathology / imaging catalogue for every hospital
-- (skips codes a hospital already has)
-- ---------------------------------------------------------------------
INSERT INTO lab_test (tenant_id, test_code, test_name, category, test_type, unit_price, mbs_item_no, mbs_schedule_fee, gst_free)
SELECT h.id, v.code, v.name, v.category, v.type, v.price, v.mbs, v.fee, TRUE
FROM hospital h
CROSS JOIN (VALUES
    ('FBC',   'Full Blood Count',                          'Haematology',  'PATHOLOGY',  45.00, '65070', 16.95),
    ('EUC',   'Electrolytes, Urea, Creatinine (EUC)',      'Biochemistry', 'PATHOLOGY',  40.00, '66500',  9.70),
    ('LIPID', 'Lipid Studies',                             'Biochemistry', 'PATHOLOGY',  50.00, '66503', 11.90),
    ('TROP',  'High-sensitivity Troponin',                 'Cardiac',      'PATHOLOGY',  95.00, '66518', 29.05),
    ('CXR',   'Chest X-Ray',                               'Imaging',      'IMAGING',   150.00, '58503', 47.15),
    ('ECG',   '12-lead ECG',                               'Cardiac',      'DIAGNOSTIC', 85.00, '11714', 32.50)
) AS v(code, name, category, type, price, mbs, fee)
WHERE NOT EXISTS (SELECT 1 FROM lab_test t WHERE t.tenant_id = h.id AND t.test_code = v.code);

-- Align the older Sydney demo entries with the standard catalogue.
UPDATE lab_test SET mbs_item_no = '66503', test_name = 'Lipid Studies' WHERE test_code = 'LIPID';
UPDATE lab_test SET active = FALSE WHERE test_code IN ('UEC', 'XRCH');   -- replaced by EUC and CXR

-- ---------------------------------------------------------------------
-- Standard medicine formulary for every hospital (skips existing names)
-- ---------------------------------------------------------------------
INSERT INTO medicine (tenant_id, medicine_name, category, unit_price, gst_rate, supply_category, stock_quantity)
SELECT h.id, v.name, v.category, v.price,
       CASE WHEN v.supply IN ('PBS', 'PRESCRIPTION') THEN 0 ELSE 0.1 END, v.supply, v.stock
FROM hospital h
CROSS JOIN (VALUES
    ('Paracetamol 500mg tablet',        'Analgesic',        0.60, 'PBS',            5000),
    ('Amoxicillin 500mg capsule',       'Antibiotic',       1.20, 'PBS',            2000),
    ('Atorvastatin 40mg tablet',        'Cardiovascular',   0.95, 'PBS',            3000),
    ('Enoxaparin 40mg injection',       'Anticoagulant',   14.50, 'PBS',             400),
    ('Ondansetron 4mg tablet',          'Antiemetic',       2.10, 'PBS',             800),
    ('Sodium chloride 0.9% 1L infusion','IV fluids',        4.80, 'PRESCRIPTION',    600),
    ('Ibuprofen 200mg tablet (OTC)',    'Analgesic',        0.35, 'OTC',            1500),
    ('Compression stockings (pair)',    'Medical supplies',38.00, 'TAXABLE_SUPPLY',  150),
    ('Antiseptic wound dressing kit',   'Medical supplies',22.00, 'TAXABLE_SUPPLY',  300)
) AS v(name, category, price, supply, stock)
WHERE NOT EXISTS (SELECT 1 FROM medicine m WHERE m.tenant_id = h.id AND lower(m.medicine_name) = lower(v.name));

-- Opening balance in the stock ledger for every medicine
INSERT INTO medicine_stock_movement (tenant_id, medicine_id, movement_type, quantity_delta, balance_after, reason,
                                     performed_by_name, performed_at)
SELECT m.tenant_id, m.id, 'OPENING', m.stock_quantity, m.stock_quantity, 'Opening balance (V5 migration)',
       'system', now()
FROM medicine m;
